#------------------------------------------------------------------------------------------#
# -- Overall Filter Parameters -- #

# Particle number parameters
min_particles: 100
max_particles: 3000

# Error parameters
kld_err: 0.02 # Maximum error between the true distribution and the estimated distribution.
kld_z: 0.99   # Upper standard normal quantile for (1 - p), where p is the probability that the error on the estimated distrubition will be less than kld_err.

# Movement update parameters
update_min_d: 0.2 # Translational movement required before performing a filter update.
update_min_a: 0.2 # Rotational movement required before performing a filter update.

# Resampling parameter
resample_interval: 1 # Number of filter updates required before resampling.

# Transform tolerance parameter 
transform_tolerance: 0.5 # Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.

# Recovery parameters 
recovery_alpha_slow: 0.0 # Exponential decay rate for the slow average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.001.
recovery_alpha_fast: 0.0 # Exponential decay rate for the fast average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.1.

# Frecuency parameters
gui_publish_rate: 50.0 # Maximum rate (Hz) at which scans and paths are published for visualization, -1.0 to disable.
save_pose_rate: 0.5 # Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server,

# Map parameters
use_map_topic: false # When set to true, AMCL will subscribe to the map topic rather than making a service call to receive its map
first_map_only: false # When set to true, AMCL will only use the first map it subscribes to, rather than updating each time a new one is received


#------------------------------------------------------------------------------------------#
# -- Laser Model Parameters -- #

laser_min_range: -1.0 # Minimum scan range to be considered; -1.0 will cause the laser's reported minimum range to be used.
laser_max_range: 10.0 # Maximum scan range to be considered; -1.0 will cause the laser's reported maximum range to be used.

laser_max_beams: 360 # How many evenly-spaced beams in each scan to be used when updating the filter.

laser_z_hit: 0.5    # Mixture weight for the z_hit part of the model.
laser_z_short: 0.05 # Mixture weight for the z_short part of the model.
laser_z_max: 0.05   # Mixture weight for the z_max part of the model.
laser_z_rand: 0.05  # Mixture weight for the z_rand part of the model.

laser_sigma_hit: 0.2 # Standard deviation for Gaussian model used in z_hit part of the model.

laser_lambda_short: 0.1 # Exponential decay parameter for z_short part of model.

laser_likelihood_max_dist: 2.0 # Maximum distance to do obstacle inflation on map, for use in likelihood_field model.

laser_model_type: likelihood_field # Which model to use, either beam, likelihood_field, or likelihood_field_prob

#------------------------------------------------------------------------------------------#
# -- Odometry Model Parameters -- #

odom_alpha1: 0.1 # Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
odom_alpha2: 0.1 # Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
odom_alpha3: 0.1 # Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
odom_alpha4: 0.1 # Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.
odom_alpha5: 0.1 # Translation-related noise parameter (only used if model is "omni" or "omni-corrected").